// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwaxmkgrjeetsnkdduzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3YXhta2dyamVldHNua2RkdXpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTQ1NDYsImV4cCI6MjA2NDA5MDU0Nn0.K-5dk2XsHcXasKHafoxPlMBwa_VM_9ZdrsTdOZ2OfTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);